import type { Metadata } from 'next';
import Link from 'next/link';
import { siteData } from '../siteData';
import { buildPageMetadata } from '../seo';

export const metadata: Metadata = buildPageMetadata({ title: 'Privacy Notice', description: 'How LOKEIL Renovation handles estimate inquiries, project details, photographs, and website information.', path: '/privacy' });

export default function PrivacyPage() {
  return <main><section className="section-space border-b border-white/8"><article className="site-shell max-w-4xl"><p className="eyebrow">Privacy notice</p><h1 className="page-title mt-4">How estimate and project information is handled.</h1><p className="lead mt-6">LOKEIL Renovation uses the information provided by phone, email, social media, or another direct inquiry channel to understand a remodeling request, prepare or discuss an estimate, and coordinate requested work.</p></article></section><section className="section-space"><article className="site-shell max-w-4xl space-y-10 text-base leading-8 text-olive-100/76"><section><h2 className="section-title">Information you provide</h2><p className="mt-5">Information may include your name, email address, phone number, property location, room details, project photographs, measurements, timing, access restrictions, material preferences, and finish references. Project photographs can contain details from inside a home, so they are used only to understand, estimate, coordinate, document, or complete the requested work.</p></section><section><h2 className="section-title">How information is used</h2><p className="mt-5">Information is used to respond to inquiries, discuss scope, prepare estimates, schedule conversations or site visits, coordinate an active project, keep necessary business records, and protect the website from abuse. LOKEIL does not sell inquiry information.</p></section><section><h2 className="section-title">Providers and security</h2><p className="mt-5">Limited information may be processed by providers used for website hosting, analytics, communications, estimating, scheduling, and recordkeeping, or shared with project participants when reasonably necessary to perform requested work. Do not send payment-card details, account passwords, or unrelated sensitive records through ordinary email.</p></section><section><h2 className="section-title">Your choices</h2><p className="mt-5">To request an eligible correction or deletion, email <a className="text-accent" href={`mailto:${siteData.email}`}>{siteData.email}</a>. Some information may be retained when reasonably required for an active project, legal obligation, safety, fraud prevention, or ordinary business records.</p></section><p className="text-sm text-olive-100/48">Updated August 21, 2026. <Link className="ml-2 text-accent" href="/contact">Contact LOKEIL</Link></p></article></section></main>;
}
